FROM ruby:2.4

MAINTAINER CONBU

RUN apt-get update -qq && apt-get install -y build-essential

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

RUN git clone https://github.com/ANNotunzdY/conbu-api-server

WORKDIR $APP_HOME/conbu-api-server

RUN git checkout feature/iw2017

RUN bundle install

EXPOSE 9292

RUN sed -i -e s/10\.255\.254\.101/0.0.0.0/g config.ru

# connect to conbu-api-daemon
RUN sed -i -e 's/localhost:8282/conbu-api-daemon:8282/g' app.rb

# change settings according to conference
RUN sed -i -e 's/phpcon2015/iw2017/g' app.rb
RUN sed -i 's/AP-\[0-9\]{3}/AP[0-9]{1,3}/g' app.rb

CMD ["bundle", "exec", "rackup", "-E", "production"]

