FROM ruby:2.4

MAINTAINER CONBU

RUN apt-get update -qq && apt-get install -y build-essential

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

RUN git clone https://github.com/conbu/conbu-api-server

WORKDIR $APP_HOME/conbu-api-server

RUN bundle install

EXPOSE 9292

RUN sed -ie s/10\.255\.254\.101/0.0.0.0/g config.ru

CMD ["bundle", "exec", "rackup", "-E", "production"]

